#ELK deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2-deployment
  labels:
    app: microservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2-service
        image: zahwaar/microservice2:1.0
        ports:
        - containerPort: 8001
---
#Microservice service 
kind: Service
apiVersion: v1
metadata:
  name: microservice2
spec:
  type: LoadBalancer
  selector:
    app: microservice2
  ports:
  - port: 80
    targetPort: 8001